### ISSUE TITLE
Some Process or way to contribute

### ISSUE THREAD

**Issue by full-story** [C0Assassin/rb4-to-rb2#13]
Hello, 
sorry if this question is a waste of time. I have a lot of the Rock Band 4 DLC and have found your work immensely useful. Is there some known process to convert RB4 songs to RB2? I would like to try and contribute the DLC I have purchased if there is some semi-automated way to do so. 

Thanks!

**Comment by C0Assassin** [comment]
There is no automatic process to convert RB4 songs down to RB1/2, its all done manually and by hand. Which is why it will take a long time to get every song converted.

All RB4 dlc songs are accessible already, so there is no need to "contribute" with anything.

**Comment by full-story** [comment]
Again, thank you so much for the work you have done. When you say "all RB4 dlc songs are accessible already," do you mean in general? I found quite a few songs that RB4 DLC songs that I have purchase from 2016 to now that are not available in this repository. Are they available elsewhere? This is why I was asking about converting them myself.

For example: 
the U2 Essentials pack
"Starships" - Nicki Minaj
"HandClap" - Fitz and the Tantrums
"Happy" - Pharrell Williams
"Sweater Weather" - The Neighbourhood
"Little Talks" - Of Monsters and Men
"Cheap Thrills" - Sia ft. Sean Paul
"Time After Time" - Cyndi Lauper
"What the Hell" - Avril Lavigne
"Royals" - Lorde
"Wake Me Up" - Avicii
"Some Nights" - fun.

Just to name a few. Have these been done?

Thank you so much for your work!

**Comment by C0Assassin** [comment]
To elaborate a bit more, since I believe there was a bit of confusion there.
By every RB4 dlc being accessible, I meant the raw files of them from a PS4 are accessible, and therefore can eventually be ported and added into this repository. All songs will eventually be added, but since this is a one man project and everything must be done by hand in order to keep the quality standard as high as it is, it will take a tremendous amount of time for the repo to catch up.

**Comment by r0bd0g** [comment]
Time After Time is in this repo.

**Comment by JarenM03** [comment]
Thank you for elaborating, @C0Assassin. We do greatly appreciate your one-man contributions. And @full-story, that's one hell of a fine song pack to suggest. :)
