### ISSUE TITLE
MGMT - KIDS

### ISSUE THREAD

**Issue by TrippyTCG** [C0Assassin/rb4-to-rb2#36]
song wont load on ONYX console. Keeps giving me: "ERROR! No songs found!"

**Comment by C0Assassin** [comment]
Ill look into it

**Comment by TrippyTCG** [comment]
thanks to you and your team for putting this archive together! yall are beasts! keep up the great work!

**Comment by C0Assassin** [comment]
The issue is that Kids has special post processing in its DTA, which causes errors in a lot of conversion tools dta parsers. 

A similar issue was just brought up recently, which also pertained to this very same inquiry. I wrote a response there in this link.
https://github.com/C0Assassin/rb4-to-rb2/issues/38#issuecomment-2035764393

Just as I stated in there before, I will not be fixing this issue as it works as intended in the games they are intended for. There should be no reason to be running any of these con files thru Onyx or C3 Tools in the first place, unless you're just repacking them. (A process that doesn't involve the DTA parser)

There are other sources to grab from if your goal is to have CH conversions. 
YARG reads CON files just fine.
Rock Band 3 reads RB1/2 cons just fine.
Onyx converting should not be necessary for practically any scenario.
