### ISSUE TITLE
R.E.M. - The One I Love and Glass Animals - Heat Waves

### ISSUE THREAD

**Issue by LostChris894** [C0Assassin/rb4-to-rb2#38]
Both of those songs are NOT convertible to Onyx.
I would like to get these songs for Clone Hero as they had been featured on Rock Band 4 and Fortnite Festival but there is nothing found on the files.
Please do fix this thank you.

**Comment by LostChris894** [comment]
Pierce the Veil - King For A Day is blocked as well too. Sorry that the files aren't accessible

**Comment by C0Assassin** [comment]
Heat Waves and King For A Day have special post proc scripting within the dta that loads in Rock Band when the game is played, so that the venue looks very striking and more dramatic compared to normal venues.

Some other songs I did this to were Electric Love, and I think Cold Heart. Theres many of them.

The problem is that automated tools have a problem with these scripts, and it bugs their parsing system.

I will not be sending fixes for any of these, since they are working just as intended in the games they are intended for. (RB1/2/3/Lego)

If you wish to convert these still, you can edit the dta and remove the context data entry that has all the post proc scripting in it. That will most likely solve the issues for all of these songs. If not, or you cannot do that, Id suggest finding another source.



The One I Love, however, has an obsolete dta entry that shouldnt be there, and I will be sending an update for that soon.

**Comment by jnackmclain** [comment]
if you are looking for ch converts just go to bit.ly/ArbystoChilis
