### ISSUE TITLE
RB4 DLC needs to be updated on ps3

### ISSUE THREAD

**Issue by thoudankeykang** [C0Assassin/RB4-to-RB2#4]
Songs like Safe And Sound, I Gotta Feeling and Cake By The Ocean are missing and Teenage Dirtbag 2020 has the art and title of the original song

**Comment by C0Assassin** [comment]
The PS3 hardware pkg is infrequently updated, there has been at least a month or more worth of updates that have been added since the PS3 hardware snapshot was uploaded.

If you really wish to get bleeding edge up to date updates for the PS3 console, you would either have to download the RPCS3 folder of the song and convert the midi to be hardware compatible, or convert one of the 360 cons into a PS3 pkg using Onyxs batch converter.
