### ISSUE TITLE
Time After Time and Hail to The king

### ISSUE THREAD

**Issue by Vipvapstevenblowjobs** [C0Assassin/rb4-to-rb2#64]
Time After Time the camera dosent work, i see can't see the characters of front. And Hail to the King the cover is other no IS the same of RB4 is the single versión?, curius because sheperd of fire have  the same cover
![IMG_20240921_180454](https://github.com/user-attachments/assets/adc4dcad-e302-4ffc-9471-76a251e99e25)
![IMG_20240921_180602](https://github.com/user-attachments/assets/ec805597-e9d8-481a-b0de-8ed49c7f25d6)

**Comment by Vipvapstevenblowjobs** [comment]
![IMG_20240921_180822](https://github.com/user-attachments/assets/3061ef88-23a2-4cd5-85c0-33e6bac556fd)


The Camera dont change position

**Comment by C0Assassin** [comment]
Hail to the King's album art was erroneously changed, and has been fixed with the newest commit: https://github.com/C0Assassin/rb4-to-rb2/commit/c5edb2c868c90f76d3ed9f3911067c317aa5186e

The camera cuts sometimes don't work on very specific hardware setups for some reason. I went thru 4 different tests with wildly different setups (vanilla/3dx/ps3/xbox), and everyone I asked said it worked. But other people had came out saying it didn't work, and I unfortunately do not have a fix for it. A temporary fix on your end can fix it, however. 
If you edit the songs dta and insert `(ugc 1)` somewhere near the bottom (maybe close to the album name or track number), it should probably work then.
