### ISSUE TITLE
Bad or missing audio

### ISSUE THREAD

**Issue by Alanzinho720** [C0Assassin/rb4-to-rb2#77]
Van Halen - Panama (bad audio)
Slayer - Angel of Death (No audio)
Architects - Animals (bad audio)

**Comment by C0Assassin** [comment]
Explain in further detail "bad audio" please, because that is very vague and I can't just magically fix something like that without an explanation.

**Comment by Alanzinho720** [comment]
> Explique com mais detalhes o que é "áudio ruim", por favor, porque isso é muito vago e não consigo consertar algo assim magicamente sem uma explicação.

The volume of the instruments is so low that you can't hear them well!

**Comment by C0Assassin** [comment]
![image](https://github.com/user-attachments/assets/e1b61d39-33c0-4e44-9565-996751cbc5f2)
Angel of Death has audio, downloaded fresh from the repo and threw it into a DAW. All audio is there, not sure where you're getting that from.

> The volume of the instruments is so low that you can't hear them well!


Most RB4 stems are naturally low volume. I increased the volume as far as I could for some songs without damaging/peaking the waveforms. Panama, Uptown Funk, and Somebody Told Me had big problems early on because of this, but where I have them now is about as good as you can realistically get without suffering quality loss.

**Comment by Alanzinho720** [comment]
I extract it using c3 tools!

**Comment by C0Assassin** [comment]
So did I!

**Comment by Alanzinho720** [comment]
I extracted the audios through onyxite and made the con files, how can I send them to you?

**Comment by Alanzinho720** [comment]
> So did I!

I extracted the audios through onyxite and made the con files, how can I send them to you?

**Comment by C0Assassin** [comment]
You are not supposed to be running these thru Onyx, it says so in big text on the front page.

**Comment by Alanzinho720** [comment]
> You are not supposed to be running these thru Onyx, it says so in big text on the front page.

Ok
